# Generated by Django 5.2.13 on 2026-05-07 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope', models.CharField(default='Full Records', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploader_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('lab', 'Lab'), ('pharma', 'Pharmacy'), ('clinic', 'Clinic')], default='patient', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('record_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='records/')),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
