# Generated by Django 5.2.13 on 2026-05-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
