# Generated by Django 5.2.13 on 2026-05-07 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('hfr_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
